# Generated by Django 4.0.2 on 2022-02-07 18:30

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='To determine the unique', primary_key=True, serialize=False)),
                ('service', models.CharField(help_text='Use for particular sservice which you want', max_length=30)),
                ('schedule', models.DateTimeField(help_text='for suggesting the time time as well as date')),
                ('status', models.BooleanField(default=False, help_text='giving the status of appointment')),
                ('rating', models.IntegerField(default=5, help_text='Give the rating for service', verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='To determine the unique', primary_key=True, serialize=False)),
                ('city', models.CharField(help_text='Patient belong to which city', max_length=30)),
                ('state', models.CharField(help_text='Patient belong to which city', max_length=20)),
                ('zipcode', models.IntegerField(help_text='City unique code ')),
            ],
        ),
    ]
