# Generated by Django 4.0.2 on 2022-02-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Using Email for Registering', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(choices=[('PATIENT', 'True'), ('DOCTOR', 'False')], help_text='for identifying the user is Whom', verbose_name=models.CharField(max_length=7)),
        ),
    ]
