# Generated by Django 4.0.2 on 2022-02-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PATIENT', 'True'), ('DOCTOR', 'False')], help_text='For identifying the user is Whom True -> doctor,False->Patient', max_length=7),
        ),
    ]
