# Generated by Django 4.0.2 on 2022-02-07 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doctor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('CL', 'Cardiologist'), ('DL', 'Dermatologists'), ('EMC', 'Emergency Medicine Specialists'), ('IL', 'Immunologists'), ('AL', 'Anesthesiologists'), ('CRS', 'Colon and Rectal Surgeons')], default='CL', max_length=3)),
                ('toTime', models.TimeField()),
                ('fromTime', models.TimeField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('rating', models.IntegerField(validators=[doctor.models.check_range])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
