# Generated by Django 4.0.2 on 2022-02-10 16:17

from django.db import migrations, models
import doctor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='For identifying the doctor ', primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('CL', 'Cardiologist'), ('DL', 'Dermatologists'), ('EMC', 'Emergency Medicine Specialists'), ('IL', 'Immunologists'), ('AL', 'Anesthesiologists'), ('CRS', 'Colon and Rectal Surgeons')], default='CL', help_text='Service which is provided by doctor', max_length=3)),
                ('toTime', models.TimeField(help_text='Starting time for doctor')),
                ('fromTime', models.TimeField(help_text='Ending time for doctor')),
                ('city', models.CharField(help_text='City Where doctor server your service', max_length=30)),
                ('state', models.CharField(help_text='State City belong too', max_length=20)),
                ('zipcode', models.IntegerField(help_text='City Zipcode')),
                ('rating', models.IntegerField(help_text='Rating Your self on the basic service knowledge', validators=[doctor.models.check_range])),
            ],
        ),
    ]
