# Generated by Django 4.0.2 on 2022-02-05 14:50

from django.db import migrations, models
import doctor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('CL', 'Cardiologist'), ('DL', 'Dermatologists'), ('EMC', 'Emergency Medicine Specialists'), ('IL', 'Immunologists'), ('AL', 'Anesthesiologists'), ('CRS', 'Colon and Rectal Surgeons')], default='CL', max_length=3)),
                ('toTime', models.TimeField()),
                ('fromTime', models.TimeField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(validators=[doctor.models.check_range])),
            ],
        ),
    ]
