# Generated by Django 4.0.2 on 2022-02-08 05:44

from django.db import migrations, models
import doctor.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(help_text='City Where doctor server your service', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fromTime',
            field=models.TimeField(help_text='Ending time for doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='For identifying the doctor ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(help_text='Rating Your self on the basic service knowledge', validators=[doctor.models.check_range]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='service',
            field=models.CharField(choices=[('CL', 'Cardiologist'), ('DL', 'Dermatologists'), ('EMC', 'Emergency Medicine Specialists'), ('IL', 'Immunologists'), ('AL', 'Anesthesiologists'), ('CRS', 'Colon and Rectal Surgeons')], default='CL', help_text='Service which is provided by doctor', max_length=3),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='state',
            field=models.CharField(help_text='State City belong too', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='toTime',
            field=models.TimeField(help_text='Starting time for doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='zipcode',
            field=models.IntegerField(help_text='City Zipcode'),
        ),
    ]
